### ISSUE TITLE
Improve paradroping following suggestions from #8

### ISSUE THREAD

**Issue by alganthe** [alganthe/Co-ops#11]
Following suggestions from #8
- Make paradroping only possible when a friendly helicopter is present within `AOSize*2` distance
- Make paradrop anywhere within the AO only for ground leaders and force non group leaders to drop on squad leaders
- Make sure i'm using PFHs this time (weren't ported when yours wrote it and I fixed it.

**Comment by alexcroox** [comment]
Doesn't this mean if there isn't a pilot online you'll never be able to paradrop? My suggestion was more geared to letting pilots do shuttle runs for infantry, rather than circling around the AO the entire mission!

I like your idea of letting people paradrop in if the heli is near the AO though, saves waiting for the pilot to fly 10k back. If the pilot is near to base the option should be disabled so they have to get onboard the heli.

**Comment by alganthe** [comment]
Good point, I'll disable paradroping if a helo with a pilot flying it is near the base.

**Comment by alganthe** [comment]
Implemented in 047722d0c8c45ae99fe458f8e617afffa355ef37

**Comment by alexcroox** [comment]
Thank you very much!

**Comment by alexcroox** [comment]
Tried the latest version and I get the "no helicopter in AO" message when I'm trying to paradrop to the AO when there are no pilots on the server at all.
